print("selamat datang di kalkulator sederhana.")
print("ketik 1 untuk menghitung penjumblahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus).")
print("ketik 6 untuk menghitung pemangkatan.")
pilihan = input("masukan pilihan anda :")
print = eval(input("masukan bilangan pertama :"))
print = input("masukan bilangan kedua :")

